/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:4365ecc8-5437-4ae2-94c1-d97f098057bc",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_R7bD3GAHv",
    "aws_user_pools_web_client_id": "74jepgpeorl0jcaqpcfhj2dvcp",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://sqvudar331.execute-api.ap-northeast-2.amazonaws.com/main",
            "region": "ap-northeast-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://cosjol2gh5fn3dhlk5cqeefmwy.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dxozfntjfvalpef7cfybeshoyq"
};


export default awsmobile;
